name: Linux with Sysdeps

on: [push, pull_request]

jobs:
  linux:
    runs-on: ubuntu-22.04
    steps:
      - name: Install build Dependencies
        run: |
          sudo apt update
          sudo apt install -y libjsoncpp-dev fakeroot libarchive-tools python3-apt zstd gettext libcurl-dev
      - name: Install angelscript
        run: |
          git clone https://github.com/anjo76/angelscript
          cd angelscript/sdk/angelscript/projects/gnuc
          make
          make install
      - name: Install socketw
        run: https://github.com/RigsOfRods/socketw && cd socketw && make install

      - uses: actions/checkout@v4

      - name: Configure
        run: cmake -DCMAKE_BUILD_TYPE=Release .

      - name: Build
        run: make -j4
